### ISSUE TITLE
install azdevops-testplan-extension via sharing 

### ISSUE THREAD

**Issue by MGana** [bryanbcook/deploymentqueuing-extension#12]
I want to use azdevops-testplan-extension
So I want to add my organization to the extension's shared list
Is it possible to share it with the organization Name: https://dev.azure.com/qa-infotech ?

**Comment by bryanbcook** [comment]
@MGana I already added the test-plan extension to your organization in https://github.com/bryanbcook/azdevops-testplan-extension/issues/24. As this is my deploymentqueuing-extension, I'm assuming this request is for this extension?

I've updated the 'shared-with' to include [qa-infotech](https://dev.azure.com/qa-infotech) in the list of organizations. Instructions on how to install the extension after it's been shared are the same as https://github.com/bryanbcook/azdevops-testplan-extension/issues/24
