### ISSUE TITLE
Include in private-preview [request]

### ISSUE THREAD

**Issue by andreafloh** [bryanbcook/deploymentqueuing-extension#13]
I would like to be included in the private preview for this extension!

Azure DevOps "Organization Name": https://dev.azure.com/andreafloh0232/

The Technology stack that best describes my scenario:

- [x] Java

Result format that I plan to use:

- [x] jUnit

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/deploymentqueuing-extension/blob/main/docs/Installation.md#install-via-sharing
