### ISSUE TITLE
Share extension request

### ISSUE THREAD

**Issue by jscrobinson** [bryanbcook/deploymentqueuing-extension#14]
Please share this extension with my Azure DevOps organization https://dev.azure.com/croudtech

Thank you

**Comment by bryanbcook** [comment]
Added. Please see the [deployment instructions][1] on how to install the shared extension.

Please open a defect if you encounter any issues.

[1]: https://github.com/bryanbcook/deploymentqueuing-extension/blob/main/docs/Installation.md#install-via-sharing
