### ISSUE TITLE
ERROR: Unable to decode file 'D:\a\_temp/cancelBuild.json' with 'utf-8' encoding.

### ISSUE THREAD

**Issue by BoredBrick** [bryanbcook/deploymentqueuing-extension#7]
After setting up the extensions and running it, I get the following output:

```
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\273cbac3-f89f-470f-9696-1b336c3c2001.ps1'"
Fetching InProgress Builds...
There are 3 in progress builds for consideration.
ERROR: Unable to decode file 'D:\a\_temp/cancelBuild.json' with 'utf-8' encoding.
 > Canceling build 277...Canceled. ()
ERROR: Unable to decode file 'D:\a\_temp/cancelBuild.json' with 'utf-8' encoding.
 > Canceling build 278...Canceled. ()
Finishing: Post-job: Cancel Queued Builds
````

After which I can see that the previous pending pipeline runs are still queued and were not cancelled.

**Comment by bryanbcook** [comment]
What's your build agent setup -- this is a self-hosted windows agent?  If self-hosted, what version of PowerShell?

Also, could you run the pipeline with `system.debug` enabled? There should be additional debug information available in the output

**Comment by BoredBrick** [comment]
It's a Microsoft-hosted agent. After trying out more things I found out it doesn't work with `pool:
  vmImage: windows-latest` setting. Changing it to `pool:
  vmImage: ubuntu-latest` works.
  
  This is the output with `system.debug:`
[output.txt](https://github.com/bryanbcook/deploymentqueuing-extension/files/13178988/output.txt)

**Comment by bryanbcook** [comment]
Thanks for this, as a hosted agent I should be able to reproduce the error at least.

Something from the log stands out for me:

```diff
2023-10-26T14:08:41.2507698Z VERBOSE: Checking build 277
+2023-10-26T14:08:42.6803267Z VERBOSE: timeline record: 
2023-10-26T14:08:43.9695348Z ERROR: Unable to decode file 'D:\a\_temp/cancelBuild.json' with 'utf-8' encoding.
+2023-10-26T14:08:44.1523463Z  > Canceling build 277...Canceled. ()
```

The timeline record appears to be empty but the [logic to cancel the pipeline](https://github.com/bryanbcook/deploymentqueuing-extension/blob/df833d4bc647c90fbc7350624e38ca4c8645b0b4/src/deployment-queuing.yml#L60C1-L75C81) continues to execute, which suggests the value is _not_ an empty array or a null value.

I can reproduce the issue when my build agent is running under windows-latest, (my team has been largely been using ubuntu agents almost exclusively). The strangest thing is that the same az-cli command on my local windows machine does not have an issue.

I think the _"Unable to decode file..."_ might be a red-herring and that the issue could be an issue in the az-cli. I'll keep investigating

**Comment by bryanbcook** [comment]
@BoredBrick should be resolved now. Please advise if you have any issues.
